artifacts_root: artifacts

data_ingestion:
  raw_data_path: artifacts/raw.csv
  train_data_path: artifacts/train.csv
  test_data_path: artifacts/test.csv
  test_size: 0.2
  random_state: 42

data_transformation:
  preprocessor_obj_file_path: artifacts/preprocessor.pkl

model_trainer:
  trained_model_file_path: artifacts/model.pkl
  model_type: RandomForestClassifier
  params:
    n_estimators: 100
    max_depth: null
    random_state: 42
